language: r
os: linux
warnings_are_errors: false
cache: packages
pandoc: true
latex: true

r_packages:
    - utils
    - rstan
    - testthat
    - roxygen2
    
r_github_packages:
  - cttedwards/sraInputs
  - cttedwards/sraInputsBio

apt_packages:
  - libudunits2-dev
  - libgdal-dev
  - libgeos-dev
  - libproj-dev
  - libv8-dev
  
script:
    - R CMD build --no-build-vignettes .
    - R CMD check .

repos:
  CRAN: https://cran.rstudio.com

notifications:
  slack:
    rooms:
    - cescape:nDRQK01fllwqCeavOIkiYSDn#srainputs

